/**
 * What the API returns when asked what a listing is worth.
 *
 * Every number here comes from the ML service or from the database; none of it
 * is ever generated by a language model. That separation is the guardrail the
 * brief asks for, and keeping the shapes in one file makes it checkable.
 */
import { z } from 'zod';
import { amdAmountSchema, isoDateTimeSchema, uuidSchema } from './common/primitives.js';

export const VALUATION_VERDICTS = ['UNDERPRICED', 'FAIR', 'OVERPRICED'] as const;
export const valuationVerdictSchema = z.enum(VALUATION_VERDICTS);
export type ValuationVerdict = z.infer<typeof valuationVerdictSchema>;

/**
 * One reason the estimate is what it is.
 *
 * `feature` is the model's own column name, which the interface translates; it
 * is deliberately not a human sentence, because the sentence has to exist in
 * three languages and the model has no opinion about which.
 */
export const valuationFactorSchema = z.object({
  feature: z.string(),
  /** The listing's value for that feature, for display: "1", "KHRUSHCHYOVKA", null when unknown. */
  value: z.union([z.string(), z.number(), z.boolean(), z.null()]),
  /** Signed share of the estimate, as a fraction: 0.12 means this raised it by 12%. */
  effect: z.number(),
  /** The same effect in dram, so the interface never has to multiply anything. */
  impactAmd: z.number(),
});
export type ValuationFactor = z.infer<typeof valuationFactorSchema>;

export const valuationSchema = z.object({
  listingId: uuidSchema,
  /** Identifies the model that produced this, and is stored with it. */
  modelVersion: z.string(),
  /** The estimate: what a comparable property is being asked for. */
  fairPriceAmd: amdAmountSchema,
  lowerBoundAmd: amdAmountSchema,
  upperBoundAmd: amdAmountSchema,
  /** Asking price against the estimate, as a percentage: 12 means 12% above it. */
  deviationPct: z.number(),
  verdict: valuationVerdictSchema,
  /** Ordered by how much they moved the estimate, largest first. */
  factors: z.array(valuationFactorSchema),
  calculatedAt: isoDateTimeSchema,
  /**
   * True when the listing has changed since this was computed, or the model has
   * moved on, and the valuation service could not reach the model to refresh it.
   * The interface still shows the figure, and says it is out of date.
   */
  isStale: z.boolean(),
});
export type Valuation = z.infer<typeof valuationSchema>;
