/**
 * What the API returns when asked what a listing is worth.
 *
 * Every number here comes from the ML service or from the database; none of it
 * is ever generated by a language model. That separation is the guardrail the
 * brief asks for, and keeping the shapes in one file makes it checkable.
 */
import { z } from 'zod';
import { buildingTypeSchema, conditionSchema, heatingTypeSchema } from './common/enums.js';
import { districtSlugSchema } from './geo.js';
import { amdAmountSchema, isoDateTimeSchema, uuidSchema } from './common/primitives.js';

export const VALUATION_VERDICTS = ['UNDERPRICED', 'FAIR', 'OVERPRICED'] as const;
export const valuationVerdictSchema = z.enum(VALUATION_VERDICTS);
export type ValuationVerdict = z.infer<typeof valuationVerdictSchema>;

/**
 * One reason the estimate is what it is.
 *
 * `feature` is the model's own column name, which the interface translates; it
 * is deliberately not a human sentence, because the sentence has to exist in
 * three languages and the model has no opinion about which.
 */
export const valuationFactorSchema = z.object({
  feature: z.string(),
  /** The listing's value for that feature, for display: "1", "KHRUSHCHYOVKA", null when unknown. */
  value: z.union([z.string(), z.number(), z.boolean(), z.null()]),
  /** Signed share of the estimate, as a fraction: 0.12 means this raised it by 12%. */
  effect: z.number(),
  /** The same effect in dram, so the interface never has to multiply anything. */
  impactAmd: z.number(),
});
export type ValuationFactor = z.infer<typeof valuationFactorSchema>;

export const valuationSchema = z.object({
  listingId: uuidSchema,
  /** Identifies the model that produced this, and is stored with it. */
  modelVersion: z.string(),
  /** The estimate: what a comparable property is being asked for. */
  fairPriceAmd: amdAmountSchema,
  lowerBoundAmd: amdAmountSchema,
  upperBoundAmd: amdAmountSchema,
  /** Asking price against the estimate, as a percentage: 12 means 12% above it. */
  deviationPct: z.number(),
  verdict: valuationVerdictSchema,
  /** Ordered by how much they moved the estimate, largest first. */
  factors: z.array(valuationFactorSchema),
  calculatedAt: isoDateTimeSchema,
  /**
   * True when the listing has changed since this was computed, or the model has
   * moved on, and the valuation service could not reach the model to refresh it.
   * The interface still shows the figure, and says it is out of date.
   */
  isStale: z.boolean(),
});
export type Valuation = z.infer<typeof valuationSchema>;

// ---------------------------------------------------------------------------
// Valuing a property that is not a listing
// ---------------------------------------------------------------------------

/**
 * What the landing page's calculator asks about a property.
 *
 * The model needs more than a reader will reliably know, so the fields it can
 * manage without are optional and the answer says what was assumed in their
 * place. Nothing here is a listing: this values a property someone is looking
 * at, which is the question the product exists to answer.
 */
export const valuationQuoteRequestSchema = z
  .object({
    districtSlug: districtSlugSchema,
    rooms: z.number().int().min(1).max(10),
    totalArea: z.number().gt(5).lte(1000),
    floor: z.number().int().min(1).max(60),
    totalFloors: z.number().int().min(1).max(60),
    buildingType: buildingTypeSchema,
    condition: conditionSchema,
    askingPriceAmd: amdAmountSchema.refine((value) => value > 0, 'Asking price is required'),

    /** Optional: assumed from the district's housing stock when not given. */
    constructionYear: z.number().int().min(1850).max(2100).optional(),
    /** Optional: assumed from the district's housing stock when not given. */
    heating: heatingTypeSchema.optional(),
    hasElevator: z.boolean().optional(),
    hasParking: z.boolean().optional(),

    /** Optional: only used to report a gross yield, never fed to the model. */
    monthlyRentAmd: amdAmountSchema.optional(),
    /** Free text from the reader. Never reaches the model; it is not a feature. */
    notes: z.string().max(1_000).optional(),
  })
  .refine((value) => value.floor <= value.totalFloors, {
    message: 'Floor cannot be above the top of the building',
    path: ['floor'],
  });
export type ValuationQuoteRequest = z.infer<typeof valuationQuoteRequestSchema>;

/** A field the reader left blank, and what was used instead. */
export const ASSUMED_FIELDS = ['constructionYear', 'heating', 'coordinates', 'interior'] as const;
export const assumedFieldSchema = z.enum(ASSUMED_FIELDS);
export type AssumedField = z.infer<typeof assumedFieldSchema>;

export const valuationAssumptionSchema = z.object({
  field: assumedFieldSchema,
  /** What was used, for display: "1975", "CENTRAL_GAS", "Kentron". */
  value: z.string(),
});
export type ValuationAssumption = z.infer<typeof valuationAssumptionSchema>;

/**
 * How much of the catalogue stands behind the estimate.
 *
 * The bands are counts of comparable listings, not a judgement about the
 * property: `THIN` means the model is extrapolating from few neighbours and the
 * figure deserves less weight, whatever it says.
 */
export const EVIDENCE_LEVELS = ['THIN', 'MODERATE', 'STRONG'] as const;
export const evidenceLevelSchema = z.enum(EVIDENCE_LEVELS);
export type EvidenceLevel = z.infer<typeof evidenceLevelSchema>;

export const valuationQuoteSchema = z.object({
  modelVersion: z.string(),
  fairPriceAmd: amdAmountSchema,
  lowerBoundAmd: amdAmountSchema,
  upperBoundAmd: amdAmountSchema,
  /** Asking price against the estimate, as a percentage: 12 means 12% above it. */
  deviationPct: z.number(),
  verdict: valuationVerdictSchema,
  /** Ordered by how much they moved the estimate, largest first. */
  factors: z.array(valuationFactorSchema),

  /** Listings in the catalogue close enough to stand behind the estimate. */
  comparableCount: z.number().int().min(0),
  evidence: evidenceLevelSchema,
  /**
   * How tight the model's range is, from 0 to 1.
   *
   * `1 − (upper − lower) / estimate`, floored at zero: a range of ±10% around
   * the estimate is 0.8, and a range as wide as the estimate itself is 0. It is
   * a property of the interval and nothing else — in particular it is not a
   * probability, and says nothing about whether the asking price is sensible.
   */
  confidence: z.number().min(0).max(1),

  /** Annual rent over the asking price, when a rent was given. */
  grossRentalYieldPct: z.number().optional(),
  /** Every field the reader left blank, and what stood in for it. */
  assumptions: z.array(valuationAssumptionSchema),
  calculatedAt: isoDateTimeSchema,
});
export type ValuationQuote = z.infer<typeof valuationQuoteSchema>;

// ---------------------------------------------------------------------------
// How well the model actually does
// ---------------------------------------------------------------------------

/**
 * The model's own cross-validation, published.
 *
 * The landing page's FAQ asks how accurate the estimates are, and the only
 * defensible answer is the one the model measured about itself. Hard-coding a
 * figure into the copy would make it a claim that silently went stale the next
 * time anything was retrained.
 *
 * Two error figures, because there are two questions. `withinKnownDistrictsMape`
 * holds out individual listings, which is the everyday case: somewhere the model
 * has seen before. `unseenDistrictMape` holds out a whole district, which asks
 * what happens somewhere it has never been. The second is always worse and is
 * the one worth quoting when someone asks whether to trust it.
 */
export const modelAccuracySchema = z.object({
  modelVersion: z.string(),
  trainedAt: z.string(),
  trainingRows: z.number().int().min(0),
  districtsCovered: z.number().int().min(0),
  /**
   * What the model was trained to predict. It is a price per square metre taken
   * from asking prices: the catalogue holds no sale prices, so no claim about
   * sale prices can be made from it.
   */
  target: z.string(),
  /** Mean absolute percentage error, holding out listings. Absent if unmeasured. */
  withinKnownDistrictsMape: z.number().optional(),
  /** The same, holding out a whole district. Absent if unmeasured. */
  unseenDistrictMape: z.number().optional(),
  /** Share of held-out listings whose true price fell inside the reported range. */
  intervalCoverage: z.number().optional(),
});
export type ModelAccuracy = z.infer<typeof modelAccuracySchema>;
