/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an account and start a session */
        post: operations["Auth.register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authenticate with email and password */
        post: operations["Auth.login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate the refresh token and issue a new access token */
        post: operations["Auth.refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End the current session */
        post: operations["Auth.logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End every session of the current user */
        post: operations["Auth.logoutAll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current account and buyer profile */
        get: operations["Users.getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update display name, phone or interface locale */
        patch: operations["Users.updateMe"];
        trace?: never;
    };
    "/api/users/me/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Save onboarding preferences (budget, rooms, priorities, commute anchor) */
        put: operations["Users.updatePreferences"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List accounts (admin) */
        get: operations["Users.listUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Change the role of an account (admin) */
        patch: operations["Users.updateRole"];
        trace?: never;
    };
    "/api/districts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All districts and towns with trilingual names and centroids */
        get: operations["Geo.listDistricts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/districts/{slug}/boundary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** District boundary as a GeoJSON MultiPolygon */
        get: operations["Geo.getBoundary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/listings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Structured search with filters, sorting and cursor pagination
         * @description Returns published listings. With mine=true it returns the caller’s own listings in any status; moderators may filter by any status.
         */
        get: operations["Listings.search"];
        put?: never;
        /**
         * Create a listing for an existing building
         * @description Any signed-in account may create one. A regular user’s listing enters the review queue; a verified agent’s is published immediately.
         */
        post: operations["Listings.create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/listings/{idOrPublicId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listing detail by id or public id */
        get: operations["Listings.getOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/listings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Archive a listing (soft delete) */
        delete: operations["Listings.archive"];
        options?: never;
        head?: never;
        /**
         * Update attributes or translations of a listing
         * @description Status is not editable here; use the transitions endpoint.
         */
        patch: operations["Listings.update"];
        trace?: never;
    };
    "/api/listings/{id}/transitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Move a listing through the moderation lifecycle
         * @description SUBMIT, PUBLISH, APPROVE, REJECT, REVISE and ARCHIVE. A transition that is not legal from the current status is a conflict, not a bad request.
         */
        post: operations["Listings.transition"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/listings/{id}/permanent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a listing and all of its history, permanently
         * @description Administrators only. Archiving is the reversible option.
         */
        delete: operations["Listings.destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/buildings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Building details */
        get: operations["Buildings.get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/buildings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a building; its district is derived from the coordinates */
        post: operations["Buildings.create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/listings/{id}/valuation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * What the model thinks this listing is worth, and why
         * @description Every figure comes from the model or the database. A stored valuation is reused while the listing is unchanged, and served with isStale set when the model cannot be reached to refresh it.
         */
        get: operations["Valuation.forListing"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rank listings against a buyer’s stated preferences
         * @description Hard limits filter the catalogue; the remainder are scored on each criterion and combined by the chosen method. Each result carries the criteria that placed it there, and a paragraph phrasing them when a model wrote one that quotes only the figures it was given. Every run is stored so rankings can be compared later.
         */
        post: operations["Recommendations.recommend"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Turn a sentence into search filters
         * @description Returns the filters that were understood and the phrases that were not. The result is never applied automatically: the caller shows it and lets the reader correct it.
         */
        post: operations["Search.parse"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search/hybrid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search by sentence: filters, words and meaning, fused
         * @description Parses the sentence into filters, ranks the listings that pass them by full-text match and by embedding similarity, and fuses the two rankings with reciprocal rank fusion. Every result reports where each arm placed it. Without an embedding index or a model service the search runs lexically and says so.
         */
        post: operations["Search.hybridSearch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["Health.check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness probe (database reachable) */
        get: operations["Health.ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterBodyDto: {
            email: string;
            password: string;
            displayName: string;
            /**
             * @default hy
             * @enum {string}
             */
            locale?: "hy" | "ru" | "en";
        };
        AuthResponseDto: {
            user: {
                /** Format: uuid */
                id: string;
                email: string;
                /** @enum {string} */
                role: "USER" | "AGENT" | "MODERATOR" | "ADMIN";
                /** @enum {string} */
                locale: "hy" | "ru" | "en";
                displayName: string;
                /** Format: date-time */
                createdAt: string;
            };
            accessToken: string;
            /** @enum {string} */
            tokenType: "Bearer";
            expiresIn: number;
        };
        LoginBodyDto: {
            email: string;
            password: string;
        };
        MeResponseDto: {
            /** Format: uuid */
            id: string;
            email: string;
            /** @enum {string} */
            role: "USER" | "AGENT" | "MODERATOR" | "ADMIN";
            /** @enum {string} */
            locale: "hy" | "ru" | "en";
            displayName: string;
            /** Format: date-time */
            createdAt: string;
            profile: {
                displayName: string;
                phone: string | null;
                budgetMinAmd: number | null;
                budgetMaxAmd: number | null;
                preferredRooms: number[];
                priorities: {
                    [key: string]: number;
                };
                commuteAnchor: {
                    lat: number;
                    lon: number;
                    label: string;
                } | null;
                /** Format: date-time */
                onboardingCompletedAt: string | null;
            } | null;
        };
        UpdateMeBodyDto: {
            displayName?: string;
            phone?: string | null;
            /** @enum {string} */
            locale?: "hy" | "ru" | "en";
        };
        PreferencesBodyDto: {
            budgetMinAmd: number | null;
            budgetMaxAmd: number | null;
            preferredRooms: number[];
            priorities: {
                [key: string]: number;
            };
            commuteAnchor: {
                lat: number;
                lon: number;
                label: string;
            } | null;
        };
        AdminUsersPageDto: {
            items: {
                /** Format: uuid */
                id: string;
                email: string;
                /** @enum {string} */
                role: "USER" | "AGENT" | "MODERATOR" | "ADMIN";
                /** @enum {string} */
                locale: "hy" | "ru" | "en";
                displayName: string;
                /** Format: date-time */
                createdAt: string;
                isActive: boolean;
                /** Format: date-time */
                updatedAt: string;
            }[];
            nextCursor: string | null;
        };
        UpdateUserRoleBodyDto: {
            /** @enum {string} */
            role: "USER" | "AGENT" | "MODERATOR" | "ADMIN";
        };
        AdminUserDto: {
            /** Format: uuid */
            id: string;
            email: string;
            /** @enum {string} */
            role: "USER" | "AGENT" | "MODERATOR" | "ADMIN";
            /** @enum {string} */
            locale: "hy" | "ru" | "en";
            displayName: string;
            /** Format: date-time */
            createdAt: string;
            isActive: boolean;
            /** Format: date-time */
            updatedAt: string;
        };
        DistrictDto: {
            /** Format: uuid */
            id: string;
            slug: string;
            /** @enum {string} */
            kind: "CITY_DISTRICT" | "TOWN";
            name: {
                hy: string;
                ru: string;
                en: string;
            };
            city: string;
            marz: string;
            centroid: {
                lat: number;
                lon: number;
            };
        };
        DistrictBoundaryResponseDto: {
            slug: string;
            boundary: {
                /** @enum {string} */
                type: "MultiPolygon";
                coordinates: (number)[][][][];
            };
        };
        ListingsPageDto: {
            items: {
                /** Format: uuid */
                id: string;
                publicId: string;
                /** @enum {string} */
                status: "DRAFT" | "PENDING_REVIEW" | "PUBLISHED" | "REJECTED" | "ARCHIVED";
                /** @enum {string} */
                locale: "hy" | "ru" | "en";
                title: string;
                priceAmd: number;
                pricePerSqmAmd: number;
                /** @enum {string} */
                originalCurrency: "AMD" | "USD" | "EUR";
                originalPrice: number | null;
                priceNegotiable: boolean;
                rooms: number;
                totalArea: number;
                floor: number;
                totalFloors: number;
                /** @enum {string} */
                buildingType: "STONE" | "PANEL" | "MONOLITH" | "KHRUSHCHYOVKA" | "STALINKA" | "NEW_BUILD";
                /** @enum {string} */
                condition: "NEEDS_REPAIR" | "OLD_RENOVATION" | "GOOD" | "EURO_RENOVATION" | "DESIGNER";
                district: {
                    slug: string;
                    name: {
                        hy: string;
                        ru: string;
                        en: string;
                    };
                };
                location: {
                    lat: number;
                    lon: number;
                };
                /** Format: uri */
                thumbnailUrl: string | null;
                /** Format: date-time */
                publishedAt: string;
            }[];
            nextCursor: string | null;
        };
        ListingDetailDto: {
            /** Format: uuid */
            id: string;
            publicId: string;
            /** @enum {string} */
            status: "DRAFT" | "PENDING_REVIEW" | "PUBLISHED" | "REJECTED" | "ARCHIVED";
            /** @enum {string} */
            locale: "hy" | "ru" | "en";
            title: string;
            priceAmd: number;
            pricePerSqmAmd: number;
            /** @enum {string} */
            originalCurrency: "AMD" | "USD" | "EUR";
            originalPrice: number | null;
            priceNegotiable: boolean;
            rooms: number;
            totalArea: number;
            floor: number;
            totalFloors: number;
            /** @enum {string} */
            buildingType: "STONE" | "PANEL" | "MONOLITH" | "KHRUSHCHYOVKA" | "STALINKA" | "NEW_BUILD";
            /** @enum {string} */
            condition: "NEEDS_REPAIR" | "OLD_RENOVATION" | "GOOD" | "EURO_RENOVATION" | "DESIGNER";
            district: {
                slug: string;
                name: {
                    hy: string;
                    ru: string;
                    en: string;
                };
            };
            location: {
                lat: number;
                lon: number;
            };
            /** Format: uri */
            thumbnailUrl: string | null;
            /** Format: date-time */
            publishedAt: string;
            description: string;
            livingArea: number | null;
            kitchenArea: number | null;
            bathrooms: number;
            ceilingHeight: number | null;
            balconyCount: number;
            hasLoggia: boolean;
            hasParking: boolean;
            hasStorage: boolean;
            /** @enum {string} */
            heating: "CENTRAL_GAS" | "INDIVIDUAL_GAS_BOILER" | "ELECTRIC" | "NONE";
            /** @enum {string} */
            ownershipDocs: "VERIFIED" | "UNVERIFIED";
            building: {
                /** Format: uuid */
                id: string;
                /** Format: uuid */
                districtId: string;
                addressLine: string;
                street: {
                    hy: string;
                    ru: string;
                    en: string;
                };
                houseNumber: string;
                /** @enum {string} */
                buildingType: "STONE" | "PANEL" | "MONOLITH" | "KHRUSHCHYOVKA" | "STALINKA" | "NEW_BUILD";
                constructionYear: number;
                totalFloors: number;
                hasElevator: boolean;
                seismicRetrofit: boolean;
                location: {
                    lat: number;
                    lon: number;
                };
            };
            media: {
                /** Format: uuid */
                id: string;
                /** @enum {string} */
                kind: "PHOTO" | "FLOOR_PLAN" | "VIDEO";
                /** Format: uri */
                url: string;
                width: number | null;
                height: number | null;
                sortOrder: number;
                isPlaceholder: boolean;
            }[];
            translations: {
                /** @enum {string} */
                locale: "hy" | "ru" | "en";
                title: string;
                description: string;
                isMachineTranslated: boolean;
            }[];
            priceHistory: {
                priceAmd: number;
                /** Format: date-time */
                recordedAt: string;
            }[];
            /** Format: uuid */
            createdById: string | null;
            rejectionReason: string | null;
            /** Format: date-time */
            reviewedAt: string | null;
            /** Format: date-time */
            submittedAt: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateListingBodyDto: {
            priceAmd: number;
            /** @default false */
            priceNegotiable?: boolean;
            /**
             * @default AMD
             * @enum {string}
             */
            originalCurrency?: "AMD" | "USD" | "EUR";
            /** @default null */
            originalPrice?: number | null;
            totalArea: number;
            /** @default null */
            livingArea?: number | null;
            /** @default null */
            kitchenArea?: number | null;
            rooms: number;
            /** @default 1 */
            bathrooms?: number;
            /** @default null */
            ceilingHeight?: number | null;
            floor: number;
            /** @default 0 */
            balconyCount?: number;
            /** @default false */
            hasLoggia?: boolean;
            /** @default false */
            hasParking?: boolean;
            /** @default false */
            hasStorage?: boolean;
            /** @enum {string} */
            condition: "NEEDS_REPAIR" | "OLD_RENOVATION" | "GOOD" | "EURO_RENOVATION" | "DESIGNER";
            /** @enum {string} */
            heating: "CENTRAL_GAS" | "INDIVIDUAL_GAS_BOILER" | "ELECTRIC" | "NONE";
            /**
             * @default UNVERIFIED
             * @enum {string}
             */
            ownershipDocs?: "VERIFIED" | "UNVERIFIED";
            /** Format: uuid */
            buildingId: string;
            translations: {
                /** @enum {string} */
                locale: "hy" | "ru" | "en";
                title: string;
                description: string;
            }[];
        };
        UpdateListingBodyDto: {
            priceAmd?: number;
            priceNegotiable?: boolean;
            /** @enum {string} */
            originalCurrency?: "AMD" | "USD" | "EUR";
            originalPrice?: number | null;
            totalArea?: number;
            livingArea?: number | null;
            kitchenArea?: number | null;
            rooms?: number;
            bathrooms?: number;
            ceilingHeight?: number | null;
            floor?: number;
            balconyCount?: number;
            hasLoggia?: boolean;
            hasParking?: boolean;
            hasStorage?: boolean;
            /** @enum {string} */
            condition?: "NEEDS_REPAIR" | "OLD_RENOVATION" | "GOOD" | "EURO_RENOVATION" | "DESIGNER";
            /** @enum {string} */
            heating?: "CENTRAL_GAS" | "INDIVIDUAL_GAS_BOILER" | "ELECTRIC" | "NONE";
            /** @enum {string} */
            ownershipDocs?: "VERIFIED" | "UNVERIFIED";
            translations?: {
                /** @enum {string} */
                locale: "hy" | "ru" | "en";
                title: string;
                description: string;
            }[];
        };
        ListingTransitionBodyDto: {
            /** @enum {string} */
            action: "SUBMIT" | "PUBLISH" | "APPROVE" | "REJECT" | "REVISE" | "ARCHIVE";
            reason?: string;
        };
        BuildingDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            districtId: string;
            addressLine: string;
            street: {
                hy: string;
                ru: string;
                en: string;
            };
            houseNumber: string;
            /** @enum {string} */
            buildingType: "STONE" | "PANEL" | "MONOLITH" | "KHRUSHCHYOVKA" | "STALINKA" | "NEW_BUILD";
            constructionYear: number;
            totalFloors: number;
            hasElevator: boolean;
            seismicRetrofit: boolean;
            location: {
                lat: number;
                lon: number;
            };
        };
        CreateBuildingBodyDto: {
            street: {
                hy: string;
                ru: string;
                en: string;
            };
            houseNumber: string;
            /** @enum {string} */
            buildingType: "STONE" | "PANEL" | "MONOLITH" | "KHRUSHCHYOVKA" | "STALINKA" | "NEW_BUILD";
            constructionYear: number;
            totalFloors: number;
            hasElevator: boolean;
            /** @default false */
            seismicRetrofit?: boolean;
            location: {
                lat: number;
                lon: number;
            };
        };
        ValuationDto: {
            /** Format: uuid */
            listingId: string;
            modelVersion: string;
            fairPriceAmd: number;
            lowerBoundAmd: number;
            upperBoundAmd: number;
            deviationPct: number;
            /** @enum {string} */
            verdict: "UNDERPRICED" | "FAIR" | "OVERPRICED";
            factors: {
                feature: string;
                value: string | number | boolean | (null);
                effect: number;
                impactAmd: number;
            }[];
            /** Format: date-time */
            calculatedAt: string;
            isStale: boolean;
        };
        RecommendationRequestDto: {
            preferences: {
                budgetAmd: number;
                /** @default 1 */
                roomsMin?: number;
                roomsMax?: number;
                areaMin?: number;
                /** @default [] */
                districts?: string[];
                anchor?: {
                    lat: number;
                    lon: number;
                };
                /**
                 * @default {
                 *       "price": 1,
                 *       "value": 1,
                 *       "size": 0.6,
                 *       "rooms": 0.8,
                 *       "location": 0.8,
                 *       "condition": 0.6,
                 *       "building": 0.4
                 *     }
                 */
                weights?: {
                    /** @default 1 */
                    price?: number;
                    /** @default 1 */
                    value?: number;
                    /** @default 0.6 */
                    size?: number;
                    /** @default 0.8 */
                    rooms?: number;
                    /** @default 0.8 */
                    location?: number;
                    /** @default 0.6 */
                    condition?: number;
                    /** @default 0.4 */
                    building?: number;
                };
            };
            /** @default 10 */
            limit?: number;
            /**
             * @default MCDA
             * @enum {string}
             */
            strategy?: "MCDA" | "LEARNED_BASELINE";
            /**
             * @default WEIGHTED_SUM
             * @enum {string}
             */
            method?: "WEIGHTED_SUM" | "TOPSIS";
            /** @default true */
            explain?: boolean;
            experimentKey?: string;
        };
        RecommendationResponseDto: {
            /** Format: uuid */
            sessionId: string;
            /** @enum {string} */
            strategy: "MCDA" | "LEARNED_BASELINE";
            /** @enum {string} */
            method: "WEIGHTED_SUM" | "TOPSIS";
            candidateCount: number;
            omittedCriteria: ("price" | "value" | "size" | "rooms" | "location" | "condition" | "building")[];
            /** @enum {string} */
            explanationSource: "model" | "cache" | "no-provider" | "quota" | "error" | "invalid" | "disabled";
            items: {
                listing: {
                    /** Format: uuid */
                    id: string;
                    publicId: string;
                    /** @enum {string} */
                    status: "DRAFT" | "PENDING_REVIEW" | "PUBLISHED" | "REJECTED" | "ARCHIVED";
                    /** @enum {string} */
                    locale: "hy" | "ru" | "en";
                    title: string;
                    priceAmd: number;
                    pricePerSqmAmd: number;
                    /** @enum {string} */
                    originalCurrency: "AMD" | "USD" | "EUR";
                    originalPrice: number | null;
                    priceNegotiable: boolean;
                    rooms: number;
                    totalArea: number;
                    floor: number;
                    totalFloors: number;
                    /** @enum {string} */
                    buildingType: "STONE" | "PANEL" | "MONOLITH" | "KHRUSHCHYOVKA" | "STALINKA" | "NEW_BUILD";
                    /** @enum {string} */
                    condition: "NEEDS_REPAIR" | "OLD_RENOVATION" | "GOOD" | "EURO_RENOVATION" | "DESIGNER";
                    district: {
                        slug: string;
                        name: {
                            hy: string;
                            ru: string;
                            en: string;
                        };
                    };
                    location: {
                        lat: number;
                        lon: number;
                    };
                    /** Format: uri */
                    thumbnailUrl: string | null;
                    /** Format: date-time */
                    publishedAt: string;
                };
                rank: number;
                score: number;
                breakdown: {
                    /** @enum {string} */
                    criterion: "price" | "value" | "size" | "rooms" | "location" | "condition" | "building";
                    score: number;
                    weight: number;
                    contribution: number;
                }[];
                explanation: {
                    highlights: {
                        /** @enum {string} */
                        criterion: "price" | "value" | "size" | "rooms" | "location" | "condition" | "building";
                        /** @enum {string} */
                        kind: "strength" | "tradeoff";
                        score: number;
                        fact?: {
                            /** @enum {string} */
                            key: "budgetHeadroomPct" | "priceVsEstimatePct" | "areaSqm" | "rooms" | "distanceM" | "buildingAgeYears";
                            value: number;
                        };
                    }[];
                    text?: string;
                };
            }[];
            /** Format: date-time */
            createdAt: string;
        };
        ParseQueryBodyDto: {
            query: string;
        };
        ParsedQueryDto: {
            query: string;
            filters: {
                priceMin?: number;
                priceMax?: number;
                roomsMin?: number;
                roomsMax?: number;
                areaMin?: number;
                areaMax?: number;
                districts?: string[];
                buildingTypes?: ("STONE" | "PANEL" | "MONOLITH" | "KHRUSHCHYOVKA" | "STALINKA" | "NEW_BUILD")[];
                conditions?: ("NEEDS_REPAIR" | "OLD_RENOVATION" | "GOOD" | "EURO_RENOVATION" | "DESIGNER")[];
                excludeGroundFloor?: boolean;
                excludeTopFloor?: boolean;
                hasElevator?: boolean;
                hasParking?: boolean;
            };
            unmapped: string[];
            /** @enum {string} */
            source: "model" | "cache" | "no-provider" | "quota" | "error" | "invalid" | "disabled";
        };
        HybridSearchBodyDto: {
            query: string;
            /** @default 20 */
            limit?: number;
            filters?: {
                priceMin?: number;
                priceMax?: number;
                roomsMin?: number;
                roomsMax?: number;
                areaMin?: number;
                areaMax?: number;
                districts?: string[];
                buildingTypes?: ("STONE" | "PANEL" | "MONOLITH" | "KHRUSHCHYOVKA" | "STALINKA" | "NEW_BUILD")[];
                conditions?: ("NEEDS_REPAIR" | "OLD_RENOVATION" | "GOOD" | "EURO_RENOVATION" | "DESIGNER")[];
                excludeGroundFloor?: boolean;
                excludeTopFloor?: boolean;
                hasElevator?: boolean;
                hasParking?: boolean;
            };
        };
        HybridSearchResponseDto: {
            query: string;
            filters: {
                priceMin?: number;
                priceMax?: number;
                roomsMin?: number;
                roomsMax?: number;
                areaMin?: number;
                areaMax?: number;
                districts?: string[];
                buildingTypes?: ("STONE" | "PANEL" | "MONOLITH" | "KHRUSHCHYOVKA" | "STALINKA" | "NEW_BUILD")[];
                conditions?: ("NEEDS_REPAIR" | "OLD_RENOVATION" | "GOOD" | "EURO_RENOVATION" | "DESIGNER")[];
                excludeGroundFloor?: boolean;
                excludeTopFloor?: boolean;
                hasElevator?: boolean;
                hasParking?: boolean;
            };
            unmapped: string[];
            /** @enum {string} */
            parseSource: "model" | "cache" | "no-provider" | "quota" | "error" | "invalid" | "disabled";
            arms: ("lexical" | "semantic")[];
            /** @enum {string} */
            semanticSkipped?: "unavailable" | "not-indexed";
            rrfK: number;
            results: {
                listing: {
                    /** Format: uuid */
                    id: string;
                    publicId: string;
                    /** @enum {string} */
                    status: "DRAFT" | "PENDING_REVIEW" | "PUBLISHED" | "REJECTED" | "ARCHIVED";
                    /** @enum {string} */
                    locale: "hy" | "ru" | "en";
                    title: string;
                    priceAmd: number;
                    pricePerSqmAmd: number;
                    /** @enum {string} */
                    originalCurrency: "AMD" | "USD" | "EUR";
                    originalPrice: number | null;
                    priceNegotiable: boolean;
                    rooms: number;
                    totalArea: number;
                    floor: number;
                    totalFloors: number;
                    /** @enum {string} */
                    buildingType: "STONE" | "PANEL" | "MONOLITH" | "KHRUSHCHYOVKA" | "STALINKA" | "NEW_BUILD";
                    /** @enum {string} */
                    condition: "NEEDS_REPAIR" | "OLD_RENOVATION" | "GOOD" | "EURO_RENOVATION" | "DESIGNER";
                    district: {
                        slug: string;
                        name: {
                            hy: string;
                            ru: string;
                            en: string;
                        };
                    };
                    location: {
                        lat: number;
                        lon: number;
                    };
                    /** Format: uri */
                    thumbnailUrl: string | null;
                    /** Format: date-time */
                    publishedAt: string;
                };
                rank: number;
                score: number;
                ranks: {
                    [key: string]: number;
                };
            }[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type RegisterBodyDto = components['schemas']['RegisterBodyDto'];
export type AuthResponseDto = components['schemas']['AuthResponseDto'];
export type LoginBodyDto = components['schemas']['LoginBodyDto'];
export type MeResponseDto = components['schemas']['MeResponseDto'];
export type UpdateMeBodyDto = components['schemas']['UpdateMeBodyDto'];
export type PreferencesBodyDto = components['schemas']['PreferencesBodyDto'];
export type AdminUsersPageDto = components['schemas']['AdminUsersPageDto'];
export type UpdateUserRoleBodyDto = components['schemas']['UpdateUserRoleBodyDto'];
export type AdminUserDto = components['schemas']['AdminUserDto'];
export type DistrictDto = components['schemas']['DistrictDto'];
export type DistrictBoundaryResponseDto = components['schemas']['DistrictBoundaryResponseDto'];
export type ListingsPageDto = components['schemas']['ListingsPageDto'];
export type ListingDetailDto = components['schemas']['ListingDetailDto'];
export type CreateListingBodyDto = components['schemas']['CreateListingBodyDto'];
export type UpdateListingBodyDto = components['schemas']['UpdateListingBodyDto'];
export type ListingTransitionBodyDto = components['schemas']['ListingTransitionBodyDto'];
export type BuildingDto = components['schemas']['BuildingDto'];
export type CreateBuildingBodyDto = components['schemas']['CreateBuildingBodyDto'];
export type ValuationDto = components['schemas']['ValuationDto'];
export type RecommendationRequestDto = components['schemas']['RecommendationRequestDto'];
export type RecommendationResponseDto = components['schemas']['RecommendationResponseDto'];
export type ParseQueryBodyDto = components['schemas']['ParseQueryBodyDto'];
export type ParsedQueryDto = components['schemas']['ParsedQueryDto'];
export type HybridSearchBodyDto = components['schemas']['HybridSearchBodyDto'];
export type HybridSearchResponseDto = components['schemas']['HybridSearchResponseDto'];
export type $defs = Record<string, never>;
export interface operations {
    "Auth.register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterBodyDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "Auth.login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginBodyDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
            /** @description Invalid credentials or disabled account */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "Auth.refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
            /** @description Missing, invalid, expired or replayed refresh token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "Auth.logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "Auth.logoutAll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "Users.getMe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponseDto"];
                };
            };
        };
    };
    "Users.updateMe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMeBodyDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponseDto"];
                };
            };
        };
    };
    "Users.updatePreferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreferencesBodyDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponseDto"];
                };
            };
        };
    };
    "Users.listUsers": {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string;
                role?: "USER" | "AGENT" | "MODERATOR" | "ADMIN";
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUsersPageDto"];
                };
            };
            /** @description Requires the ADMIN role */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "Users.updateRole": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserRoleBodyDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserDto"];
                };
            };
            /** @description Requires the ADMIN role */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "Geo.listDistricts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DistrictDto"][];
                };
            };
        };
    };
    "Geo.getBoundary": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DistrictBoundaryResponseDto"];
                };
            };
            /** @description Unknown district slug */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "Listings.search": {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string;
                locale?: "hy" | "ru" | "en";
                sort?: "published_desc" | "price_asc" | "price_desc" | "price_per_sqm_asc" | "price_per_sqm_desc" | "area_asc" | "area_desc";
                status?: "DRAFT" | "PENDING_REVIEW" | "PUBLISHED" | "REJECTED" | "ARCHIVED";
                mine?: "true" | "false";
                priceMin?: number;
                priceMax?: number;
                pricePerSqmMax?: number;
                roomsMin?: number;
                roomsMax?: number;
                areaMin?: number;
                areaMax?: number;
                floorMin?: number;
                floorMax?: number;
                ceilingMin?: number;
                yearMin?: number;
                yearMax?: number;
                districts?: string | string[];
                buildingTypes?: string | string[];
                conditions?: string | string[];
                heating?: string | string[];
                excludeGroundFloor?: "true" | "false";
                excludeTopFloor?: "true" | "false";
                hasElevator?: "true" | "false";
                hasParking?: "true" | "false";
                hasBalcony?: "true" | "false";
                hasStorage?: "true" | "false";
                seismicRetrofit?: "true" | "false";
                docsVerified?: "true" | "false";
                priceNegotiable?: "true" | "false";
                nearLat?: number;
                nearLon?: number;
                radiusM?: number;
                bbox?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingsPageDto"];
                };
            };
        };
    };
    "Listings.create": {
        parameters: {
            query?: {
                /** @description Response locale for listing texts; falls back to the account preference, then Accept-Language, then hy */
                locale?: "hy" | "ru" | "en";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateListingBodyDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingDetailDto"];
                };
            };
            /** @description The account already holds its maximum of live listings */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "Listings.getOne": {
        parameters: {
            query?: {
                /** @description Response locale for listing texts; falls back to the account preference, then Accept-Language, then hy */
                locale?: "hy" | "ru" | "en";
            };
            header?: never;
            path: {
                idOrPublicId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingDetailDto"];
                };
            };
            /** @description Unknown, or not visible to the caller */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "Listings.archive": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not the owner and not a moderator */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "Listings.update": {
        parameters: {
            query?: {
                /** @description Response locale for listing texts; falls back to the account preference, then Accept-Language, then hy */
                locale?: "hy" | "ru" | "en";
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateListingBodyDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingDetailDto"];
                };
            };
            /** @description Not the owner */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "Listings.transition": {
        parameters: {
            query?: {
                /** @description Response locale for listing texts; falls back to the account preference, then Accept-Language, then hy */
                locale?: "hy" | "ru" | "en";
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ListingTransitionBodyDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingDetailDto"];
                };
            };
            /** @description The caller may not perform this transition */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Illegal from the listing’s current status */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "Listings.destroy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Requires ADMIN */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "Buildings.get": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuildingDto"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "Buildings.create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBuildingBodyDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuildingDto"];
                };
            };
            /** @description Address already registered in that district */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Coordinates fall outside every supported district */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "Valuation.forListing": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValuationDto"];
                };
            };
            /** @description Unknown, or not visible to the caller */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No model is deployed and nothing has been valued before */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "Recommendations.recommend": {
        parameters: {
            query?: {
                /** @description Response locale for listing texts */
                locale?: "hy" | "ru" | "en";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecommendationRequestDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationResponseDto"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "Search.parse": {
        parameters: {
            query?: {
                locale?: "hy" | "ru" | "en";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParseQueryBodyDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParsedQueryDto"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "Search.hybridSearch": {
        parameters: {
            query?: {
                locale?: "hy" | "ru" | "en";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HybridSearchBodyDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HybridSearchResponseDto"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "Health.check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process is running */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "Health.ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ready to serve traffic */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Database unreachable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
