"""
Renders the evaluation chapter from a training run.

The document is generated rather than written by hand so its numbers can never
drift from the model that is actually deployed. The prose lives here, in version
control, next to the code that produces the figures it describes.
"""

from __future__ import annotations

from typing import Any

from app.pipelines.evaluate import CrossValidationResult

_HEADER = """# Valuation model — evaluation

<!--
  GENERATED by `pnpm ml:train`. Edit the renderer in
  `apps/ml/app/pipelines/report.py`, not this file: the numbers below come from
  the training run that produced the deployed artefact, and hand-editing them
  would break that link.
-->
"""


def _metrics_row(label: str, metrics: dict[str, Any]) -> str:
    return (
        f"| {label} | {metrics['n']} | {metrics['maeAmd']:,} | {metrics['rmseAmd']:,} "
        f"| {metrics['mape'] * 100:.1f}% | {metrics['r2']:.3f} |"
    )


def render_report(
    *,
    model_version: str,
    trained_at: str,
    training_rows: int,
    districts: tuple[str, ...],
    dataset_fingerprint: str,
    results: dict[str, CrossValidationResult],
    importance: list[dict[str, Any]],
    lightgbm_version: str,
) -> str:
    """Build the whole document."""
    random_cv = results["random"]
    grouped_cv = results["grouped"]

    lines: list[str] = [_HEADER]

    lines.append(
        f"**Model** `{model_version}` · trained {trained_at} on {training_rows} published "
        f"listings across {len(districts)} districts · LightGBM {lightgbm_version} · dataset "
        f"`{dataset_fingerprint[:16]}…`\n"
    )

    lines.append("""## What is predicted, and why in that form

The model learns the natural log of **price per square metre**, not the asking price.

Two reasons. First, floor area is by far the largest driver of a total price, and predicting the
total lets a model look accurate simply by learning that bigger flats cost more; dividing it out
forces the model to earn its score on everything else. Second, the effects in this market are
multiplicative rather than additive. A renovation adds a percentage to a flat's value, not a fixed
number of dram, and the same renovation is worth more in Kentron than in Nor Nork. Taking the log
turns those proportional effects into additive ones, which is what a squared-error objective
assumes and what makes an additive SHAP decomposition meaningful.

Predictions are converted back to dram before anything is scored, so every figure below is an
error in the unit a buyer actually sees.
""")

    lines.append("""## How it is validated

| Scheme | What is held out | What it answers |
| --- | --- | --- |
| Random k-fold | Listings at random | Pricing a flat in a district it knows |
| Grouped | Whole districts, one per fold | Whether anything transfers to an unseen district |

The grouped scheme is the honest one and it is always the worse number. Yerevan's price level
varies severalfold between districts, and a model that has never been shown a district has no way
to know its level; all it can carry across is the shape of the effects, plus whatever the distance
to the centre tells it. The gap between the two rows is therefore a measure of how much of the
model's apparent accuracy is neighbourhood memory.

Both schemes refit the model and the baseline inside every fold, so no test listing is ever seen
during training.
""")

    lines.append("## Results\n")
    lines.append("| Model | n | MAE, AMD | RMSE, AMD | MAPE | R² |")
    lines.append("| --- | ---: | ---: | ---: | ---: | ---: |")
    lines.append(_metrics_row("LightGBM, random k-fold", random_cv.model.to_json()))
    lines.append(_metrics_row("Baseline (area only), random k-fold", random_cv.baseline.to_json()))
    lines.append(_metrics_row("LightGBM, grouped by district", grouped_cv.model.to_json()))
    lines.append(
        _metrics_row("Baseline (area only), grouped by district", grouped_cv.baseline.to_json())
    )
    lines.append("")

    lines.append(_versus_baseline(random_cv, grouped_cv))

    lines.append(f"""## The prediction interval

The service returns a range as well as a point estimate, from two further boosters fitted at the
10th and 90th percentiles of the same log target. An 80% interval should contain
about 80% of asking prices.

| Scheme | Raw | Calibrated |
| --- | ---: | ---: |
| Random k-fold | {random_cv.coverage * 100:.1f}% | {random_cv.coverage_calibrated * 100:.1f}% |
| Grouped | {grouped_cv.coverage * 100:.1f}% | {grouped_cv.coverage_calibrated * 100:.1f}% |

The raw interval does not keep its promise. Quantile regression on a few hundred rows is
optimistic about its own accuracy, and the left column shows by how much. The service therefore
widens it by a single multiplicative factor, measured on out-of-fold predictions by conformalised
quantile regression (Romano, Patterson and Candès, 2019); the stored factor is
`intervalLogOffset` in the artefact metadata.

Coverage matters more than it looks: the "fair price" badge calls a listing mispriced when its
asking price falls outside this range, so an interval that is too narrow would label ordinary
listings as bargains and traps.
""")

    lines.append("## What the model leans on\n")
    lines.append("| Feature | Share of total gain |")
    lines.append("| --- | ---: |")
    for entry in importance[:10]:
        lines.append(f"| `{entry['feature']}` | {entry['share'] * 100:.1f}% |")
    lines.append("")
    lines.append("""Gain-based importance describes the model as a whole. Individual listings are
explained with exact TreeSHAP values instead, computed by LightGBM itself, because a buyer asking
why *this* flat is priced as it is cannot use an average.
""")

    lines.append("""## Honest limitations

- **The data is synthetic.** Listings are generated by the seed in
  `apps/api/prisma/seed`, from an explicit multiplicative price model plus log-normal noise of
  roughly 10 to 14% per district. The model is therefore recovering a structure that is known to
  exist, and its error cannot fall below that noise. These figures measure the pipeline, the
  feature engineering and the validation design; they are not evidence about the real Yerevan
  market, and the thesis should not present them as such.
- **The sample is small.** A few hundred listings is enough to fit a shallow ensemble and not
  enough to justify a hyperparameter search: any search at this size would tune itself to the
  validation folds. The hyperparameters are fixed and stated in `evaluate.py`. One value was
  chosen from evidence rather than assumed, the number of boosting rounds, by comparing three
  candidates on out-of-fold error; that is a single-parameter choice on a one-dimensional grid,
  not a search, and it is reported here because a reader should be told which numbers were tuned.
- **Grouped validation is pessimistic by construction.** Holding out an entire district removes
  the single strongest predictor for those listings. A production system would keep district-level
  price levels updated from recent transactions rather than asking the model to infer them.
- **Asking prices, not sale prices.** The target is what a seller asks, which in any real market
  sits above what a buyer pays. Every number the interface shows is described as an estimate of
  the asking price for a comparable property.
""")

    return "\n".join(lines).rstrip() + "\n"


def _improvement(result: CrossValidationResult) -> float:
    """
    Change in mean absolute error against the area-only baseline, as a
    percentage. Positive means the model is better; negative means it is worse,
    which is a result in its own right and is reported rather than hidden.
    """
    baseline = result.baseline.mae_amd
    if baseline <= 0:
        return 0.0
    return (1 - result.model.mae_amd / baseline) * 100


def _versus_baseline(random_cv: CrossValidationResult, grouped_cv: CrossValidationResult) -> str:
    """The comparison the brief asks for, written whichever way it came out."""
    on_district = _improvement(random_cv)
    off_district = _improvement(grouped_cv)

    opening = (
        f"Within a district it knows, the model cuts mean absolute error by "
        f"**{on_district:.0f}%** against a straight line through floor area alone, which is the "
        f"baseline the brief asks for."
    )
    if off_district > 0:
        return (
            f"{opening} Held out of a district entirely it still leads, by {off_district:.0f}%.\n"
        )
    return (
        f"{opening} Held out of a district entirely it **loses to that baseline by "
        f"{abs(off_district):.0f}%**, and that is the more interesting number.\n\n"
        "The reason is structural rather than a defect. Almost everything the model knows about "
        "price level is attached to the district, so a fold that has never seen one is left "
        "predicting from the shape of a flat and its distance to the centre. The baseline is "
        "refitted inside the same fold and quietly gets to use the price level of every other "
        "district through its intercept, which on a city-wide average is a stronger position "
        "than an informed guess about an unknown neighbourhood. The practical reading is that "
        "this model must not be pointed at a city it has no data for: extending SmartEstate to "
        "Gyumri or Vanadzor means collecting listings there, not trusting the Yerevan model to "
        "generalise.\n"
    )
